### ISSUE TITLE
Control Panel bug relating to the Rectify11 Control Center

### ISSUE THREAD

**Issue by StickyChannel92** [Rectify11/RectifyControlPanel2#3] opened 2023-11-06 09:34 UTC
Case 1: When Rectify11 Control Center is opened, then closed immediately, Control Panel won't open ever again until the machine has rebooted.
Case 2: When it's opened, going to Control Panel home in the same window causes the window to not respond. If closed, the Control Panel can be opened again. But not in Case 1!

**Steps to reproduce:**
Open Rectify11 Control Center and when it opens, immediately close it.
OR
Open it and then go to the home page of Control Panel in same window.

Rectify11 version 3.1

22H2 build 22621.2428

**Comment by MishaProductions** [comment] 2023-11-08 16:24
duplicate of #2

**Closed by MishaProductions** 2023-11-08 16:24 UTC
