### ISSUE TITLE
Rectify11 new control panel applet is not responding in w11 23h2  

### ISSUE THREAD

**Issue by joefikri** [Rectify11/RectifyControlPanel2#2] opened 2023-11-03 03:19 UTC
Rectify11 new control panel applet is not responding in w11 23h2. It makes new context menu cannot be apply

**Comment by WildByDesign** [comment] 2023-12-29 11:11
@MishaProductions I spent about an hour last night digging into this issue where the Control Panel applet works once and then never again until after a reboot.

So I did some bisecting of commits until I narrowed it down:

Last good working commit without issue: https://github.com/Rectify11/RectifyControlPanel2/commit/a6d8dffb06e9c886fcd4228c29885eca9607a238

Fails to build: https://github.com/Rectify11/RectifyControlPanel2/commit/b47e3e0ef7090e4c3a329045a02d9e63b4c7c273

Builds but doesn't run: https://github.com/Rectify11/RectifyControlPanel2/commit/b47e3e0ef7090e4c3a329045a02d9e63b4c7c273

The nail in the coffin: https://github.com/Rectify11/RectifyControlPanel2/commit/52307e304188fe562e0d454a88fa15e619faa0ef

That last commit makes memory-related changes and therefore I assume must be the root of this issue. I am not a programmer, but I hope that this information is helpful.

**Comment by MishaProductions** [comment] 2023-12-29 19:16
Thanks for your investigation, the root cause does seem related to using HeapAlloc() instead of using the default memory manager. However, removing that code for whatever reason causes a crash when DirrectUI tries to create an instance of the custom class. For some weird reason this does not occur on Windows 10.

**Comment by MishaProductions** [comment] 2023-12-29 20:18
I forgot that the default memory allocator does not set everything to 0, unlike HeapAlloc which directUI uses, which caused that crash

**Comment by WildByDesign** [comment] 2023-12-30 00:40
> However, removing that code for whatever reason causes a crash when DirrectUI tries to create an instance of the custom class.

If, for some reason you cannot fix this issue, would it be possible to achieve this without using a custom class?

> For some weird reason this does not occur on Windows 10.

There always seems to be a handful of strange issues in Windows 11 that are not present in Windows 10. Also, I recall reading a few years back that there was a lot of changes to memory management in Windows 11.

> I forgot that the default memory allocator does not set everything to 0, unlike HeapAlloc which directUI uses, which caused that crash

Does this mean that you have a hint at a possible fix?

**Comment by MishaProductions** [comment] 2024-01-02 00:53
> If, for some reason you cannot fix this issue, would it be possible to achieve this without using a custom class?
that's what I did previously, but I don't like that solution as it only allows for 1 instance of the rectify control panel to be open
> Does this mean that you have a hint at a possible fix?
It seems like something is wrong at https://github.com/Rectify11/RectifyControlPanel2/blob/master/Rectify11CPL/Templetes.h

**Comment by MishaProductions** [comment] 2024-01-02 01:19
I found the issue! The CritSecLock was never released, causing the class info never to be destroyed

**Comment by MishaProductions** [comment] 2024-01-02 01:37
Fixed in 9f1c39105061b158dc5b39c72b58f7b0667c199c

**Closed by MishaProductions** 2024-01-02 01:37 UTC

**Comment by WildByDesign** [comment] 2024-01-02 03:13
Awesome work, man. This is fantastic.
